group2path = {
    0: [{"endpoint": "instruction", "theme": True},
        {"endpoint": "task", "task_num": 0, "theme": True},
        {"endpoint": "task", "task_num": 1, "theme": True},
        {"endpoint": "task", "task_num": 2, "theme": True},
        {"endpoint": "task", "task_num": 3, "theme": True},
        {"endpoint": "hold", "theme": True},
        {"endpoint": "task", "task_num": 0, "theme": True},
        {"endpoint": "task", "task_num": 1, "theme": True},
        {"endpoint": "task", "task_num": 2, "theme": True},
        {"endpoint": "task", "task_num": 3, "theme": True},
        {"endpoint": "post", "theme": True}],

    1: [{"endpoint": "instruction", "theme": True},
        {"endpoint": "task", "task_num": 0, "theme": True},
        {"endpoint": "task", "task_num": 1, "theme": True},
        {"endpoint": "task", "task_num": 2, "theme": True},
        {"endpoint": "task", "task_num": 3, "theme": True},
        {"endpoint": "hold", "theme": True},
        {"endpoint": "task", "task_num": 0, "theme": False},
        {"endpoint": "task", "task_num": 1, "theme": False},
        {"endpoint": "task", "task_num": 2, "theme": False},
        {"endpoint": "task", "task_num": 3, "theme": False},
        {"endpoint": "post", "theme": True}],

    2: [{"endpoint": "instruction", "theme": True},
        {"endpoint": "task", "task_num": 0, "theme": True},
        {"endpoint": "task", "task_num": 1, "theme": True},
        {"endpoint": "task", "task_num": 2, "theme": True},
        {"endpoint": "task", "task_num": 3, "theme": True},
        {"endpoint": "forget", "theme": True},
        {"endpoint": "task", "task_num": 0, "theme": False},
        {"endpoint": "task", "task_num": 1, "theme": False},
        {"endpoint": "task", "task_num": 2, "theme": False},
        {"endpoint": "task", "task_num": 3, "theme": False},
        {"endpoint": "post", "theme": True}],
}
