group2path = {
    0: [{"endpoint": "intro", "task_num": 0, "theme": True},
        {"endpoint": "task", "task_num": 0, "theme": True},
        {"endpoint": "task", "task_num": 1, "theme": True},
        {"endpoint": "task", "task_num": 2, "theme": True},
        {"endpoint": "task", "task_num": 3, "theme": True},
        {"endpoint": "hold", "task_num": 0, "theme": True},
        {"endpoint": "task", "task_num": 0, "theme": True},
        {"endpoint": "task", "task_num": 1, "theme": True},
        {"endpoint": "task", "task_num": 2, "theme": True},
        {"endpoint": "task", "task_num": 3, "theme": True},
        {"endpoint": "post", "task_num": 0, "theme": True}],

    1: [{"endpoint": "intro", "task_num": 0, "theme": True},
        {"endpoint": "task", "task_num": 0, "theme": True},
        {"endpoint": "task", "task_num": 1, "theme": True},
        {"endpoint": "task", "task_num": 2, "theme": True},
        {"endpoint": "task", "task_num": 3, "theme": True},
        {"endpoint": "hold", "task_num": 0, "theme": True},
        {"endpoint": "task", "task_num": 0, "theme": False},
        {"endpoint": "task", "task_num": 1, "theme": False},
        {"endpoint": "task", "task_num": 2, "theme": False},
        {"endpoint": "task", "task_num": 3, "theme": False},
        {"endpoint": "post", "task_num": 0, "theme": False}],

    2: [{"endpoint": "intro", "task_num": 0, "theme": True},
        {"endpoint": "task", "task_num": 0, "theme": True},
        {"endpoint": "task", "task_num": 1, "theme": True},
        {"endpoint": "task", "task_num": 2, "theme": True},
        {"endpoint": "task", "task_num": 3, "theme": True},
        {"endpoint": "forget", "task_num": 0, "theme": True},
        {"endpoint": "task", "task_num": 0, "theme": False},
        {"endpoint": "task", "task_num": 1, "theme": False},
        {"endpoint": "task", "task_num": 2, "theme": False},
        {"endpoint": "task", "task_num": 3, "theme": False},
        {"endpoint": "post", "task_num": 0, "theme": False}],
}
